[project]
name = "paradakusz-zebrafish-macrophage-analysis"
version = "0.2.0"
description = "Pipeline to analyze 3D images of zebrafish"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imaris-ims-file-reader>=0.1.8",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "scikit-image>=0.26.0",
    "tifffile>=2026.8.23",
    "xarray>=2026.7.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
]

[build-system]
requires = ["uv_build>=0.11.26,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "shared"
module-root = ""
